name: country_explorer
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  get: ^4.7.3
  google_fonts: ^7.0.0
  hive_flutter: ^1.1.0
  http: ^1.6.0
  iconsax_flutter: ^1.0.1
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0
  hive: ^2.2.3
  path_provider: ^2.1.0
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/app_logo/
